version: '3.8'

services:
  drupal:
    build: .
    ports:
      - "80:80"
    volumes:
      - drupal_files:/var/www/html/sites/default/files
    depends_on:
      - db
    networks:
      - drupal_network
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_USER=${DB_USER}
      - DRUPAL_DB_PASSWORD=${DB_PASSWORD}
      - DRUPAL_DB_NAME=${DB_NAME}

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - drupal_network      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    networks:
      - drupal_network
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  drupal_files:
  mysql_data:

networks:
  drupal_network:
